# .travis.yml - 2019-02-24
#
# (cc) <paul4hough@gmail.com>

sudo: false
dist: xenial
language: ruby
notifications:
  email:
    - paul4hough@gmail.com

before_script:
  - uname -a
  - env
  - bundle install

script:
  - bundle exec rake test
